/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/ModelX.glb 
*/
import React, { useRef } from 'react'
import { useSnapshot } from "valtio"

import { Preload, useGLTF } from '@react-three/drei'
import { useCustomization } from '../context/Customization';
import { state } from '../components/ColorPicker';


export function ModelX(props) {
  const { nodes, materials } = useGLTF('models/ModelX.glb')
  const { overlay } = useCustomization()
  const snap1 = useSnapshot(state)

  const canvasRef = useRef(document.createElement("canvas"));
  const textureRef = useRef();
  const context = useRef(canvasRef.current.getContext("2d"));
console.log()

  canvasRef.current.width = 1600;
  canvasRef.current.height = 1600;

  let ctx = context.current;

  ctx.globalCompositeOperation = "hue";

  const img = document.getElementById(`overlay${overlay}`);

  if (img.complete) {
    ctx.drawImage(img, 0, 0);
    if (snap1.base.BaseMtl !== "none") {
      if(overlay!==1){
      ctx.fillStyle = snap1.base.BaseMtl;
      ctx.fillRect(0, 0, 1600, 1600);
      }
    }


    if (textureRef.current) {
      textureRef.current.needsUpdate = true;
    }
  }

  else {
    img.onload = function () {
      ctx.drawImage(img, 0, 0);
      if (snap1.base.BaseMtl !== "none") {
        if(overlay!==1){
        ctx.fillStyle = snap1.base.BaseMtl;
        ctx.fillRect(0, 0, 1600, 1600);
        }
      }
      


      if (textureRef.current) {
        textureRef.current.needsUpdate = true;
      }
    }
  }
  return (
    <group {...props} dispose={null}>
      <group position={[-0.856, 0.391, 1.55]} rotation={[-Math.PI, 0, 0]} scale={-1}>
        <mesh geometry={nodes.Circle021.geometry} material={materials.chromeRuff} />
        <mesh geometry={nodes.Circle024.geometry} material={materials.rims} position={[0.131, 0, 0]} />
        <mesh geometry={nodes.Circle025.geometry} material={materials.rims} position={[0.131, 0, 0]} />
        <mesh geometry={nodes.Circle026.geometry} material={materials.rims} position={[0.131, 0, 0]} />
        <mesh geometry={nodes.Circle033.geometry} material={materials.tires} rotation={[0, 0, -Math.PI]} scale={-1} />
        <mesh geometry={nodes.Circle034.geometry} material={materials.tires} rotation={[0, 0, -Math.PI]} scale={-1} />
        <mesh geometry={nodes.Circle063.geometry} material={materials.Brake_disk_red} position={[0.028, -0.003, -0.174]} scale={-1} />
        <mesh geometry={nodes.Circle064.geometry} material={materials.Brake_disk_red} position={[0.031, -0.134, -0.151]} scale={-1} />
        <mesh geometry={nodes.Circle065.geometry} material={materials.rubber_black} position={[0.028, -0.003, -0.174]} scale={-1} />
        <mesh geometry={nodes.Circle066.geometry} material={nodes.Circle066.material} position={[0.028, -0.003, -0.174]} scale={-1} />
        <mesh geometry={nodes.Circle067.geometry} material={nodes.Circle067.material} position={[0.028, -0.003, -0.174]} scale={-1} />
        <mesh geometry={nodes.Circle068.geometry} material={nodes.Circle068.material} position={[0.028, -0.003, -0.174]} scale={-1} />
        <mesh geometry={nodes.Circle069.geometry} material={materials.chrome_dark_1} position={[0.028, -0.003, -0.174]} scale={-1} />
        <mesh geometry={nodes.Circle071.geometry} material={materials.caliper} position={[0.039, 0, 0]} rotation={[0, 0, -Math.PI / 2]} scale={-1} />
        <mesh geometry={nodes.Circle072.geometry} material={materials.brakeDisk} position={[0.028, -0.003, -0.174]} />
        <mesh geometry={nodes.NurbsPath007.geometry} material={materials.Brake_disk_red} position={[0.058, -0.1, -0.167]} />
      </group>
      <group position={[-0.856, 0.391, -1.408]} rotation={[-Math.PI, 0, 0]} scale={-1}>
        <mesh geometry={nodes.Circle017.geometry} material={materials.rims} position={[0.131, 0, 0]} />
        <mesh geometry={nodes.Circle061.geometry} material={materials.Brake_disk_red} position={[0.028, -0.003, -0.174]} scale={-1} />
        <mesh geometry={nodes.Circle060.geometry} material={materials.Brake_disk_red} position={[0.031, -0.134, -0.151]} scale={-1} />
        <mesh geometry={nodes.Circle059.geometry} material={materials.rubber_black} position={[0.028, -0.003, -0.174]} scale={-1} />
        <mesh geometry={nodes.Circle058.geometry} material={nodes.Circle058.material} position={[0.028, -0.003, -0.174]} scale={-1} />
        <mesh geometry={nodes.Circle057.geometry} material={nodes.Circle057.material} position={[0.028, -0.003, -0.174]} scale={-1} />
        <mesh geometry={nodes.Circle056.geometry} material={nodes.Circle056.material} position={[0.028, -0.003, -0.174]} scale={-1} />
        <mesh geometry={nodes.Circle055.geometry} material={materials.chrome_dark_1} position={[0.028, -0.003, -0.174]} scale={-1} />
        <mesh geometry={nodes.NurbsPath006.geometry} material={materials.Brake_disk_red} position={[0.058, -0.1, -0.167]} />
        <mesh geometry={nodes.Circle011.geometry} material={materials.tires} rotation={[-0.841, 0, -Math.PI]} scale={-1} />
        <mesh geometry={nodes.Circle015.geometry} material={materials.rims} position={[0.131, 0, 0]} />
        <mesh geometry={nodes.Circle016.geometry} material={materials.rims} position={[0.131, 0, 0]} />
        <mesh geometry={nodes.Circle018.geometry} material={materials.tires} rotation={[-0.841, 0, -Math.PI]} scale={-1} />
        <mesh geometry={nodes.Circle020.geometry} material={materials.chromeRuff} />
        <mesh geometry={nodes.Circle053.geometry} material={materials.brakeDisk} position={[0.028, -0.003, -0.174]} />
        <mesh geometry={nodes.Circle054.geometry} material={materials.caliper} position={[0.039, 0, 0]} rotation={[0, 0, -Math.PI / 2]} scale={-1} />
      </group>
      <group position={[0.856, 0.391, -1.408]} rotation={[-0.841, 0, -Math.PI]} scale={-1}>
        <mesh geometry={nodes.Circle012.geometry} material={materials.rims} position={[0.131, 0, 0]} />
        <mesh geometry={nodes.Circle043.geometry} material={materials.Brake_disk_red} position={[0.028, 0.128, 0.119]} rotation={[-0.841, 0, Math.PI]} />
        <mesh geometry={nodes.Circle044.geometry} material={materials.Brake_disk_red} position={[0.031, 0.023, 0.2]} rotation={[-0.841, 0, Math.PI]} />
        <mesh geometry={nodes.Circle045.geometry} material={materials.rubber_black} position={[0.028, 0.128, 0.119]} rotation={[-0.841, 0, Math.PI]} />
        <mesh geometry={nodes.Circle046.geometry} material={nodes.Circle046.material} position={[0.028, 0.128, 0.119]} rotation={[-0.841, 0, Math.PI]} />
        <mesh geometry={nodes.Circle047.geometry} material={nodes.Circle047.material} position={[0.028, 0.128, 0.119]} rotation={[-0.841, 0, Math.PI]} />
        <mesh geometry={nodes.Circle048.geometry} material={nodes.Circle048.material} position={[0.028, 0.128, 0.119]} rotation={[-0.841, 0, Math.PI]} />
        <mesh geometry={nodes.Circle049.geometry} material={materials.chrome_dark_1} position={[0.028, 0.128, 0.119]} rotation={[-0.841, 0, Math.PI]} />
        <mesh geometry={nodes.NurbsPath005.geometry} material={materials.Brake_disk_red} position={[0.058, 0.057, 0.186]} rotation={[-0.841, 0, Math.PI]} scale={-1} />
        <mesh geometry={nodes.Circle013.geometry} material={materials.rims} position={[0.131, 0, 0]} />
        <mesh geometry={nodes.Circle009.geometry} material={materials.chromeRuff} />
        <mesh geometry={nodes.Circle014.geometry} material={materials.rims} position={[0.131, 0, 0]} />
        <mesh geometry={nodes.Circle029.geometry} material={materials.tires} />
        <mesh geometry={nodes.Circle030.geometry} material={materials.tires} />
        <mesh geometry={nodes.Circle051.geometry} material={materials.caliper} position={[0.039, 0, 0]} rotation={[-0.841, 0, Math.PI / 2]} />
        <mesh geometry={nodes.Circle052.geometry} material={materials.brakeDisk} position={[0.028, 0.128, 0.119]} rotation={[-0.841, 0, Math.PI]} scale={-1} />
      </group>
      <group position={[0.856, 0.391, 1.55]} rotation={[0.496, 0, -Math.PI]} scale={-1}>
        <mesh geometry={nodes.Circle005.geometry} material={materials.rims} position={[0.131, 0, 0]} />
        <mesh geometry={nodes.Circle028.geometry} material={materials.tires} />
        <mesh geometry={nodes.Circle042.geometry} material={materials.Brake_disk_red} position={[0.028, -0.086, 0.152]} rotation={[0.496, 0, -Math.PI]} />
        <mesh geometry={nodes.Circle041.geometry} material={materials.Brake_disk_red} position={[0.031, -0.19, 0.069]} rotation={[0.496, 0, -Math.PI]} />
        <mesh geometry={nodes.Circle040.geometry} material={materials.rubber_black} position={[0.028, -0.086, 0.152]} rotation={[0.496, 0, -Math.PI]} />
        <mesh geometry={nodes.Circle039.geometry} material={nodes.Circle039.material} position={[0.028, -0.086, 0.152]} rotation={[0.496, 0, -Math.PI]} />
        <mesh geometry={nodes.Circle038.geometry} material={nodes.Circle038.material} position={[0.028, -0.086, 0.152]} rotation={[0.496, 0, -Math.PI]} />
        <mesh geometry={nodes.Circle037.geometry} material={nodes.Circle037.material} position={[0.028, -0.086, 0.152]} rotation={[0.496, 0, -Math.PI]} />
        <mesh geometry={nodes.Circle036.geometry} material={materials.chrome_dark_1} position={[0.028, -0.086, 0.152]} rotation={[0.496, 0, -Math.PI]} />
        <mesh geometry={nodes.NurbsPath004.geometry} material={materials.Brake_disk_red} position={[0.058, -0.168, 0.099]} rotation={[0.496, 0, -Math.PI]} scale={-1} />
        <mesh geometry={nodes.Circle004.geometry} material={materials.rims} position={[0.131, 0, 0]} />
        <mesh geometry={nodes.Circle.geometry} material={materials.rims} position={[0.131, 0, 0]} />
        <mesh geometry={nodes.Circle003.geometry} material={materials.tires} />
        <mesh geometry={nodes.Circle006.geometry} material={materials.caliper} position={[0.039, 0, 0]} rotation={[0.496, 0, Math.PI / 2]} />
        <mesh geometry={nodes.Circle008.geometry} material={materials.chromeRuff} />
        <mesh geometry={nodes.Circle035.geometry} material={materials.brakeDisk} position={[0.028, -0.086, 0.152]} rotation={[0.496, 0, -Math.PI]} scale={-1} />
      </group>
      <mesh geometry={nodes.Plane051.geometry} material={materials.black_plastic_3} position={[0, 0.841, 0]} />
      <mesh geometry={nodes.Plane050.geometry} material={materials.chrome_rough_3} position={[0, 0.841, 0]} />
      <mesh geometry={nodes.Plane044.geometry} material={materials.rims} position={[0, 0.841, 0]} />
      <mesh geometry={nodes.Plane042.geometry} material={materials.rims} position={[0, 0.841, 0]} />
      <mesh geometry={nodes.Plane041.geometry} material={materials.chrome_rough_1} position={[1.117, 0.894, 1.184]} rotation={[0, Math.PI / 2, 0]} scale={0.31} />
      <mesh geometry={nodes.Plane037.geometry} material={materials.chrome_shiny} position={[0, 0.841, 0]} />
      <mesh geometry={nodes.Plane032.geometry} material={materials.chrome_dark_2} position={[0, 0.841, 0]} />
      <mesh geometry={nodes.Plane026.geometry} material={materials['headlight_cover_glass 2']} position={[0, 0.841, 0]} />
      <mesh geometry={nodes.Plane024.geometry} material={materials.black_plastic_shiny} position={[-0.004, 0.841, 0.004]} />
      <mesh geometry={nodes.Plane020.geometry} material={materials.headlight_pattern_orange} position={[-0.004, 0.841, 0.004]} />
      <mesh geometry={nodes.Plane016.geometry} material={materials.carPaint} position={[0, 0.841, 0]} />
      <mesh geometry={nodes.Plane013.geometry} material={materials.rims} position={[0, 0.841, 0]} />
      <mesh geometry={nodes.Plane149.geometry} material={materials.carPaint} position={[0, 0.841, 0]} />
      <mesh geometry={nodes.Plane122.geometry} material={materials.black_plastic} position={[0, 0.841, -0.042]} />
      <mesh geometry={nodes.Plane121.geometry} material={materials.carPaint} position={[0, 0.841, -0.042]} />
      <mesh geometry={nodes.Plane028.geometry} material={nodes.Plane028.material} position={[0, 0.841, 0]} />
      <mesh geometry={nodes.Plane082.geometry} material={materials.glass} position={[0, 0.841, 0]} />
      <mesh geometry={nodes.Plane069.geometry} material={materials.headlights} position={[0, 0.841, 0]} />
      <mesh geometry={nodes.Plane067.geometry} material={materials.chrome_rough_1} position={[0, 0.841, 0]} />
      <mesh geometry={nodes.Plane066.geometry} material={materials.rims} position={[0, 0.841, 0]} />
      <mesh geometry={nodes.Plane065.geometry} material={materials.glass} position={[0, 0.841, 0]} />
      <mesh geometry={nodes.Plane064.geometry} material={materials.rims} position={[0, 0.841, 0]} />
      <mesh geometry={nodes.Plane063.geometry} material={materials.carPaint} position={[0, 0.841, 0]} />
      <mesh geometry={nodes.Plane021.geometry} material={materials.rims} position={[0, 0.841, 0]} />
      <mesh geometry={nodes.Plane062.geometry} material={materials.rims} position={[0, 0.841, 0]} />
      <mesh geometry={nodes.Plane059.geometry} material={materials.rims} position={[0, 0.841, 0]} />
      <mesh geometry={nodes.Plane058.geometry} material={materials.headlights} position={[0, 0.841, 0]} />
      <mesh geometry={nodes.Body.geometry} position={[0, 0.841, 0]}>
        <meshStandardMaterial {...materials.BaseMtl} color={overlay==1 || overlay==13 ? (snap1.base.BaseMtl!=="none" ? snap1.base.BaseMtl : 0xffffff) : 0xffffff}>
          <canvasTexture
            flipY={false}
            wrapS={1000}
            wrapT={1000}
            colorSpace='srgb'
            ref={textureRef}
            attach="map"
            image={canvasRef.current}
          />
        </meshStandardMaterial>
      </mesh>
      <mesh geometry={nodes.Plane052.geometry} material={materials.brakeDisk} position={[0, 0.841, 0]} />
      <mesh geometry={nodes.Plane049.geometry} material={materials.carPaint} position={[0, 0.841, 0]} />
      <mesh geometry={nodes.Plane048.geometry} material={materials.carPaint} position={[0, 0.841, 0]} />
      <mesh geometry={nodes.Plane046.geometry} material={materials.carPaint} position={[0, 0.841, 0]} />
      <mesh geometry={nodes.Plane061.geometry} material={materials.rims} position={[0, 1.226, -5.023]} />
      <mesh geometry={nodes.Plane047.geometry} material={materials.carPaint} position={[0, 0.841, 0]} />
      <mesh geometry={nodes.Plane045.geometry} material={materials.glass} position={[0, 0.841, 0]} />
      <mesh geometry={nodes.Plane034.geometry} material={materials.carPaint} position={[0, 0.841, 0]} />
      <mesh geometry={nodes.Plane043.geometry} material={materials.carPaint} position={[0, 0.841, 0]} />
      <mesh geometry={nodes.Plane019.geometry} material={materials.carPaint} position={[0, 0.841, 0]} />
      <mesh geometry={nodes.Plane033.geometry} material={materials.black_plastic} position={[0, 0.841, 0]} />
      <mesh geometry={nodes.Plane030.geometry} material={materials.black_plastic_shiny} position={[0, 0.841, 0]} />
      <mesh geometry={nodes.Plane029.geometry} material={materials.black_plastic_shiny} position={[0, 0.841, 0]} />
      <mesh geometry={nodes.Plane027.geometry} material={materials.glass} position={[0, 0.841, 0]} />
      <mesh geometry={nodes.Plane025.geometry} material={materials.black_plastic_shiny} position={[0, 0.841, 0]} />
      <mesh geometry={nodes.Plane023.geometry} material={materials.rims} position={[0, 0.841, 0]} />
      <mesh geometry={nodes.Plane022.geometry} material={materials.carPaint} position={[0, 0.841, 0]} />
      <mesh geometry={nodes.Plane007.geometry} material={materials.carPaint} position={[0, 0.841, 0]} />
      <mesh geometry={nodes.Plane018.geometry} material={materials.carPaint} position={[0, 0.841, 0]} />
      <mesh geometry={nodes.Plane017.geometry} material={materials.carPaint} position={[0, 0.841, 0]} />
      <mesh geometry={nodes.Plane015.geometry} material={materials.chromeRuff} position={[0, 0.841, 0]} />
      <mesh geometry={nodes.Plane014.geometry} material={materials.glass} position={[0, 0.841, 0]} />
      <mesh geometry={nodes.Plane012.geometry} material={materials.rims} position={[0, 0.841, 0]} />
      <mesh geometry={nodes.Plane011.geometry} material={materials.chrome_rough_2} position={[0, 0.841, 0]} />
      <mesh geometry={nodes.Plane008.geometry} material={materials.rims} position={[0, 0.84, 0]} />
      <mesh geometry={nodes.Plane003.geometry} material={materials.rims} position={[0, 0.841, 0]} />
      <mesh geometry={nodes.Plane001.geometry} material={materials.black_plastic} position={[0, 0.841, 0]} />
      <mesh geometry={nodes.Plane151.geometry} material={materials.headlight_cover_glass_3} position={[0.735, 1.053, -2.142]} />
      <mesh geometry={nodes.Plane150.geometry} material={materials.headlight_cover_glass_3} position={[0.735, 1.053, -2.142]} />
      <mesh geometry={nodes.Plane120.geometry} material={materials.chrome_shiny} position={[0, 0.841, 0]} />
      <mesh geometry={nodes.Plane119.geometry} material={materials.redLight} position={[0, 0.841, 0]} />
      <mesh geometry={nodes.Plane111.geometry} material={materials.carPaint} position={[0, 0.841, 0]} />
      <mesh geometry={nodes.Plane110.geometry} material={materials.redLight} position={[0, 0.841, 0]} />
      <mesh geometry={nodes.Plane109.geometry} material={materials.black_plastic} position={[0, 0.841, 0]} />
      <mesh geometry={nodes.Plane108.geometry} material={materials.headlight_cover_glass_3} position={[0.824, 0.969, -2.142]} />
      <mesh geometry={nodes.Plane101.geometry} material={materials.chromeRuff} position={[0, 0.841, 0]} />
      <mesh geometry={nodes.Plane100.geometry} material={materials.chromeRuff} position={[0, 0.841, 0]} />
      <mesh geometry={nodes.Plane095.geometry} material={materials.black_plastic_3} position={[0, 0.841, 0]} />
      <mesh geometry={nodes.Plane081.geometry} material={materials.rims} position={[0, 0.841, 0]} />
      <mesh geometry={nodes.Plane080.geometry} material={materials.chrome_shiny_blue} position={[0, 0.841, 0]} />
      <mesh geometry={nodes.Plane079.geometry} material={nodes.Plane079.material} position={[0, 0.841, 0]} />
      <mesh geometry={nodes.Plane078.geometry} material={materials.rims} position={[0, 0.841, 0]} />
      <mesh geometry={nodes.Plane075.geometry} material={materials.rims} position={[0, 0.841, 0]} />
      <mesh geometry={nodes.Plane074.geometry} material={materials.redLight} position={[0, 0.841, 0]} />
      <mesh geometry={nodes.Plane072.geometry} material={materials.rims} position={[0, 0.841, 0]} />
      <mesh geometry={nodes.Plane070.geometry} material={materials.chromeRuff} position={[0, 0.841, 0]} />
      <mesh geometry={nodes.Plane039.geometry} material={materials.carPaint} position={[0, 0.841, 0]} />
      <mesh geometry={nodes.Plane091.geometry} material={materials.carPaint} position={[0, 0.841, 0]} />
      <mesh geometry={nodes.Curve005.geometry} material={materials.rims} position={[0.484, 0.798, -2.813]} rotation={[Math.PI / 2, 0, -Math.PI]} scale={[0.329, 0.329, 0.164]} />
      <mesh geometry={nodes.Curve.geometry} material={materials.chrome_shiny} position={[0, 1.049, -2.698]} rotation={[Math.PI / 2, 0, -Math.PI]} scale={0.219} />
    </group>
  )
}

useGLTF.preload('/ModelX.glb')
